/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "ble.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(WhiteItem, WhiteItem, AUTO)


PB_BIND(WhiteList, WhiteList, AUTO)


PB_BIND(bluetooth_device_pb, bluetooth_device_pb, AUTO)


PB_BIND(WhiteListResponse, WhiteListResponse, AUTO)


PB_BIND(WhiteListRequest, WhiteListRequest, AUTO)





