/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7-dev */

#include "lane.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(LaneLengthConfig, LaneLengthConfig, AUTO)


PB_BIND(LaneColorConfig, LaneColorConfig, AUTO)


PB_BIND(LaneSetStatus, LaneSetStatus, AUTO)


PB_BIND(LaneSetSpeed, LaneSetSpeed, AUTO)


PB_BIND(LaneState, LaneState, AUTO)


PB_BIND(LaneConfig, LaneConfig, AUTO)


PB_BIND(LaneConfigRO, LaneConfigRO, AUTO)


PB_BIND(LaneControl, LaneControl, AUTO)


PB_BIND(PbLanePace, PbLanePace, AUTO)




#ifndef PB_CONVERT_DOUBLE_FLOAT
/* On some platforms (such as AVR), double is really float.
 * To be able to encode/decode double on these platforms, you need.
 * to define PB_CONVERT_DOUBLE_FLOAT in pb.h or compiler command line.
 */
PB_STATIC_ASSERT(sizeof(double) == 8, DOUBLE_MUST_BE_8_BYTES)
#endif

