---
name: CI

# yamllint disable-line rule:truthy
on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
  workflow_dispatch:

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - {
              dir: "build_debug_64",
              build_type: "Debug",
              without_64_bit: "OFF"
            }
          - {
            dir: "build_debug_32",
            build_type: "Debug",
            without_64_bit: "ON"
          }
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v2.3.4

      - name: Installing dependencies for local act
        if: ${{ env.ACT }}
        run: |
          sudo apt update
          sudo apt install -y cmake
          sudo apt install -y build-essential

      - name: Installing common dependencies
        run: |
          sudo apt install -y python3-protobuf protobuf-compiler

      - name: Setup build vars
        run: |
          echo '::set-output name=BUILD_DIR::${{ matrix.config.dir }}'
        id: build_vars

      - name: 🏗 Configure
        shell: bash
        run: |
          mkdir ${{ steps.build_vars.outputs.BUILD_DIR }}
          cmake \
            -S . \
            -B ${{ steps.build_vars.outputs.BUILD_DIR }} \
            -DCMAKE_BUILD_TYPE=${{ matrix.config.build_type }} \
            -DBUILD_TESTS=ON \
            -DBUILD_EXAMPLES=ON \
            -DPB_WITHOUT_64BIT=${{ matrix.config.build_type }}

      - name: 🚀 Build
        shell: bash
        run: |
          cmake --build ${{ steps.build_vars.outputs.BUILD_DIR }}

      - name: Run tests
        shell: bash
        run: |
          cd ${{ steps.build_vars.outputs.BUILD_DIR }}
          ctest

      - name: Run example
        shell: bash
        run: |
          cd ${{ steps.build_vars.outputs.BUILD_DIR }}
          examples/complex/complex


